/** @type {import('tailwindcss').Config} */
export default {
content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
darkMode: 'class',
theme: {
  extend: {
    scale: { 98: '0.98' },
    colors: {
      'surface-container-highest': '#d7e5eb',
      'inverse-surface': '#0b0f10',
      'inverse-on-surface': '#9a9d9f',
      'on-secondary-fixed': '#354052',
      'on-secondary': '#f8f8ff',
      tertiary: '#5c5d78',
      'surface-container-high': '#dfeaef',
      'on-surface-variant': '#546166',
      'surface-tint': '#095fae',
      'on-tertiary': '#fbf7ff',
      'on-tertiary-container': '#4b4c67',
      'on-surface': '#283439',
      'outline-variant': '#a7b4ba',
      'secondary-container': '#d8e3fa',
      'surface-bright': '#f7fafc',
      'primary-fixed-dim': '#bdd6ff',
      'primary-fixed': '#d5e3ff',
      primary: '#095fae',
      'on-primary-fixed-variant': '#005cab',
      'on-error': '#fff7f6',
      surface: '#f7fafc',
      'tertiary-fixed-dim': '#cdccec',
      'primary-container': '#d5e3ff',
      'error-container': '#fe8983',
      'surface-dim': '#ccdde4',
      'secondary-dim': '#495467',
      'error-dim': '#4e0309',
      'tertiary-container': '#dbdafb',
      'on-secondary-fixed-variant': '#515c6f',
      secondary: '#546073',
      'surface-variant': '#d7e5eb',
      'secondary-fixed': '#d8e3fa',
      'surface-container': '#e7eff3',
      'on-error-container': '#752121',
      'on-tertiary-fixed': '#393a53',
      'inverse-primary': '#6ba8fc',
      'secondary-fixed-dim': '#cad5ec',
      'tertiary-fixed': '#dbdafb',
      background: '#f7fafc',
      outline: '#707d82',
      'on-tertiary-fixed-variant': '#555671',
      'on-primary-fixed': '#004079',
      'surface-container-lowest': '#ffffff',
      error: '#9f403d',
      'tertiary-dim': '#50516c',
      'on-background': '#283439',
      'on-primary-container': '#005299',
      'surface-container-low': '#eff4f7',
      'primary-dim': '#00539b',
      'on-primary': '#f6f7ff',
      'on-secondary-container': '#475265',
    },
    fontFamily: {
      headline: ['Inter', 'sans-serif'],
      body: ['Inter', 'sans-serif'],
      label: ['Inter', 'sans-serif'],
    },
    borderRadius: {
      DEFAULT: '0.125rem',
      lg: '0.25rem',
      xl: '0.5rem',
      full: '0.75rem',
    },
  },
},
plugins: [],
}